# >>> NAO EDITE ESTE ARQUIVO <<<
# Logica em: ebravo-br/cicd-templates/.github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    if: toJson(github.event.commits) != '[]'
    uses: ebravo-br/cicd-templates/.github/workflows/ci.yml@v1
